In [16]:
from matplotlib import pyplot as plt
import pandas as pd
import numpy as np
import seaborn as sb

In [17]:
# Importing dataset
churn = pd.read_csv('C:/Users/Amrutha Mukundan/Desktop/Data_Science/Swarup_Practice/Churn_Modelling.csv')
churn.shape

(10000, 14)

In [18]:
churn.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [19]:
X = churn.iloc[:, 3:13].values
y = churn.iloc[:,13].values
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [20]:
y

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

In [21]:
# Encoding categorical data
# Encoding the column Geography
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:,1] = labelencoder_X_1.fit_transform(X[:,1])
# Encoding the column Gender
labelencoder_X_2 = LabelEncoder()
X[:,2] = labelencoder_X_2.fit_transform(X[:,2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]
X

C:\Users\Amrutha Mukundan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\Amrutha Mukundan\Anaconda3\lib\site-packages\sklearn\preprocessing\_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


array([[0.0000000e+00, 0.0000000e+00, 6.1900000e+02, ..., 1.0000000e+00,
        1.0000000e+00, 1.0134888e+05],
       [0.0000000e+00, 1.0000000e+00, 6.0800000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 1.1254258e+05],
       [0.0000000e+00, 0.0000000e+00, 5.0200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 1.1393157e+05],
       ...,
       [0.0000000e+00, 0.0000000e+00, 7.0900000e+02, ..., 0.0000000e+00,
        1.0000000e+00, 4.2085580e+04],
       [1.0000000e+00, 0.0000000e+00, 7.7200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 9.2888520e+04],
       [0.0000000e+00, 0.0000000e+00, 7.9200000e+02, ..., 1.0000000e+00,
        0.0000000e+00, 3.8190780e+04]])

### Train-test split using loop

In [22]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(churn.loc[:, churn.columns != 'Exited'], 
                                                    churn['Exited'], stratify=churn['Exited'], random_state = 66) 
from sklearn.neighbors import KNeighborsClassifier
training_accuracy = []
testing_accuracy = []
 # Try n neighbors from 1 to 20
neighbors_settings = range(1,20)
for i in neighbors_settings:
    # build the model
    knn = KNeighborsClassifier(n_neighbors = i)
    knn.fit(X_train, y_train)
    # Record training accuracy
    training_accuracy.append(knn.score(X_train, y_train))
    # Record testing accuracy
    testing_accuracy.append(knn.score(X_test, y_test))
plt.plot(neighbors_settings, training_accuracy , label ='training accuracy')
plt.plot(neighbors_settings, testing_accuracy , label ='testing accuracy')
plt.xlabel('n_neighbors')
plt.ylabel('Accuracy')
plt.legend()

ValueError: could not convert string to float: 'Bezrukova'

In [ ]:
knn = KNeighborsClassifier(n_neighbors = 9)
knn.fit(X_train, y_train)
knn.score(X_test, y_test)

In [ ]:
print('Accuracy of knn classifer on train dataset : {:.2f}'.format(knn.score(X_train, y_train)))
print('Accuracy of knn classifer on test dataset : {:.2f}'.format(knn.score(X_test, y_test)))

In [23]:
predictions = knn.predict(X_train)

ValueError: could not convert string to float: 'Bezrukova'